---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    runtime: shiny
---

```{r setup, include=FALSE,eval = TRUE}
library(flexdashboard)
library(dplyr)
library(ggplot2)
#library(tidyverse)
require(shiny)
require(plotly)

data <- read.csv("SchoolGrades18.csv",stringsAsFactors = FALSE)
#data <- read.csv("K:\\A&A Docs\\Aaron Smith\\ComparableSchools\\SchoolGrades18.csv",stringsAsFactors = FALSE)
#data <- as.data.frame(readxl::read_excel("K:\\A&A Docs\\Aaron Smith\\ComparableSchools\\SchoolGrades18.xls",skip = 3))
data <- data[order(data[,"School.Name"]),]
data <- data[order(data[,"District.Name"]),]
data[,"School"] <- paste0(data[,"District.Name"],"; ",data[,"School.Name"])
data <- dplyr::bind_rows(data[data[,"District.Name"] == "SEMINOLE",],data[data[,"District.Name"] != "SEMINOLE",])
rownames(data) <- data[,"School"]
for(j in 1:ncol(data)){
  if(class(data[,j]) == "integer"){
    data[,j] <- as.numeric(data[,j])
  }
}

elementary <- data[data[,"School.Type"] == 1 & data[,"Charter.School"] == "NO",]
middle <- data[data[,"School.Type"] == 2 & data[,"Charter.School"] == "NO",]
high <- data[data[,"School.Type"] == 3 & data[,"Charter.School"] == "NO",]
other <- data[data[,"School.Type"] == 4 | data[,"Charter.School"] == "YES",]

D.elementary <- as.matrix(dist(elementary[,c("Percent.of.Minority.Students","Percent.of.Economically.Disadvantaged.Students")],method = "maximum"))
D.elementary <- D.elementary[,!grepl(x = colnames(D.elementary),pattern = "SEMINOLE;")]
M.elementary <- D.elementary
for(j in 1:nrow(M.elementary)) M.elementary[j,] <- colnames(D.elementary)[order(D.elementary[j,])]
colnames(M.elementary) <- 1:ncol(M.elementary)
elementary <- data.frame(elementary,M.elementary)

D.middle <- as.matrix(dist(middle[,c("Percent.of.Minority.Students","Percent.of.Economically.Disadvantaged.Students")],method = "maximum"))
D.middle <- D.middle[,!grepl(x = colnames(D.middle),pattern = "SEMINOLE;")]
M.middle <- D.middle
for(j in 1:nrow(M.middle)) M.middle[j,] <- colnames(D.middle)[order(D.middle[j,])]
colnames(M.middle) <- 1:ncol(M.middle)
middle <- data.frame(middle,M.middle)

D.high <- as.matrix(dist(high[,c("Percent.of.Minority.Students","Percent.of.Economically.Disadvantaged.Students")],method = "maximum"))
D.high <- D.high[,!grepl(x = colnames(D.high),pattern = "SEMINOLE;")]
M.high <- D.high
for(j in 1:nrow(M.high)) M.high[j,] <- colnames(D.high)[order(D.high[j,])]
colnames(M.high) <- 1:ncol(M.high)
high <- data.frame(high,M.high)

D.other <- as.matrix(dist(other[,c("Percent.of.Minority.Students","Percent.of.Economically.Disadvantaged.Students")],method = "maximum"))
D.other <- D.other[,!grepl(x = colnames(D.other),pattern = "SEMINOLE;")]
M.other <- D.other
for(j in 1:nrow(M.other)) M.other[j,] <- colnames(D.other)[order(D.other[j,])]
colnames(M.other) <- 1:ncol(M.other)
other <- data.frame(other,M.other)

#seminole <- dplyr::bind_rows(
#  elementary[grepl(x = rownames(elementary),pattern = "SEMINOLE;"),],
#  middle[grepl(x = rownames(middle),pattern = "SEMINOLE;"),],
#  high[grepl(x = rownames(high),pattern = "SEMINOLE;"),],
#  other[grepl(x = rownames(other),pattern = "SEMINOLE;"),]
#)

#nonseminole <- dplyr::bind_rows(
#  elementary[!grepl(x = rownames(elementary),pattern = "SEMINOLE;"),],
#  middle[!grepl(x = rownames(middle),pattern = "SEMINOLE;"),],
#  high[!grepl(x = rownames(high),pattern = "SEMINOLE;"),],
#  other[!grepl(x = rownames(other),pattern = "SEMINOLE;"),]
#)

elementary <- elementary[,sapply(X = elementary,FUN = function(x) mean(is.na(x))) < 0.5]
middle <- middle[,sapply(X = middle,FUN = function(x) mean(is.na(x))) < 0.5]
high <- high[,sapply(X = high,FUN = function(x) mean(is.na(x))) < 0.5]
other <-  other[,sapply(X = other,FUN = function(x) mean(is.na(x))) < 0.5]
```

Elementary
=======================================================================

Column {data-width=350}
-----------------------------------------------------------------------

### Selections:

Data source: 
[http://www.fldoe.org/accountability/accountability-reporting/school-grades/](http://www.fldoe.org/accountability/accountability-reporting/school-grades/)

```{r}
selectInput(
  "seminole_school",
  label = "Seminole School",
  choices = rownames(elementary)[toupper(elementary$District.Name) == "SEMINOLE"]
)

selectInput(
  "number_of_schools",
  label = "Select the number of schools",
  choices = c(5,10,25,50,100,200,300,nrow(elementary) - sum(elementary$District.Name == "SEMINOLE") - 1)
)



elementary.variables <- c(
    "English Language Arts Achievement","English Language Arts Learning Gains","English Language Arts Learning Gains of the Lowest 25 ",
    "Mathematics Achievement","Mathematics Learning Gains","Mathematics Learning Gains of the Lowest 25 ",
    "Science Achievement","Social Studies Achievement",
    "Middle School Acceleration","Graduation Rate 2016 17","College and Career Acceleration 2016 17",
    "Total Points Earned","Total Components","Percent of Total Possible Points","Percent Tested"
  )
elementary.variables <- elementary.variables[make.names(elementary.variables) %in% colnames(elementary)]

selectInput(
  "variable",
  label = "Variable to plot",
  choices = elementary.variables
)
variable <- reactive({make.names(input$variable)})

closest.elementary <- reactive({
  elementary[
    c(input$seminole_school,
    t(elementary[input$seminole_school,paste0("X",1:input$number_of_schools)])),
  ]
#  c("District.Name","School.Name","Percent.of.Minority.Students","Percent.of.Economically.Disadvantaged.Students",variable())
})


```

### Scatterplot of comparable schools

```{r}
renderPlotly({
  p <- ggplot(elementary) + 
    aes(x = Percent.of.Minority.Students,y =   Percent.of.Economically.Disadvantaged.Students) + 
    geom_point(colour = "#80808080") + 
    #ggtitle("Scatterplot of Florida Elementary Schools",subtitle = "% Minority and % Economically Disadvantaged") +
    xlab("% Minority") + 
    ylab("% Economically Disadvantaged") + 
    labs(caption = "Data Source: http://www.fldoe.org/accountability/accountability-reporting/school-grades/, 2018-07-20") + 
  geom_point(data = closest.elementary(),colour = "blue",size = 2,,mapping = aes(District = District.Name,School = School.Name))  + 
  geom_point(data = elementary[input$seminole_school,],colour = "red",size = 3)
  ggplotly(p,tooltip = c("District","School"))
})
```

Column {data-width=650}
-----------------------------------------------------------------------

### Data table of comparable schools

```{r}
library(DT)
renderDataTable({
  datatable(
    closest.elementary()[,!grepl(x = colnames(closest.elementary()),pattern = "X")], rownames = FALSE, 
    extensions = 'Buttons', options = list(
      dom = 'Bfrtip',
      buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
    ), fillContainer =TRUE
  )
})
#renderPrint({
#  print(closest.elementary()[,variable()])
#})
```

### Dot plot of data from comparable schools

```{r,eval = TRUE,echo = FALSE}
renderPlot({
#  boxplot(closest.elementary()[,variable()],horizontal = TRUE,col = "steelblue",main = paste0("Boxplot of ",variable()," data from comparable schools"))
  stripchart(closest.elementary()[,variable()],method = "stack",col = "blue",offset = 0.7,main = paste0("Dot plot of ",variable()," data from comparable schools"),pch = 19,ylim = c(1,1.5*max(table(closest.elementary()[,variable()]))))
  abline(v = closest.elementary()[1,variable()],col = "red")
  legend("topleft",lty = 1,col = "red",legend = gsub(x = input$seminole_school,pattern = "SEMINOLE; ",replacement = ""))
    axis(1,closest.elementary()[,variable()])
  })
```
```{r,eval = FALSE,echo = FALSE}
renderPlotly({
  dotplot.elementary <- ggplot(closest.elementary()) +
    geom_dotplot(aes(x = variable()))
  ggplotly(dotplot.elementary)
  
})
```
